import { describe, expect, it } from 'vitest'
import sheet from './combatPickSheet.vue?raw'
import encounter from './encounterPanel.vue?raw'
import herb from './herbPvpPanel.vue?raw'
import mine from './treasureMinePanel.vue?raw'

describe('combat pick sheet', () => {
  it('is the only worker pick list, shared by PVE orders, treasure mines, and herb mowing', () => {
    expect(sheet).toContain('class="pick-slot"')
    expect(sheet).toContain('pickSlotNumber')
    expect(encounter).toContain(':slot-offset="pickSlotOffset"')
    expect(mine).toContain(':slot-offset="pickSlotOffset"')
    expect(sheet).toContain('class="pick-list"')
    expect(sheet).toContain('enemyPickCopy')
    expect(sheet).toContain('v-if="showRunes"')
    expect(encounter).toContain('<CombatPickSheet')
    expect(encounter).not.toContain('class="pick-list"')
    expect(mine).toContain('<CombatPickSheet')
    expect(mine).toContain(':show-runes="pickKind === \'raid\'"')
    expect(mine).toContain(':show-assist="false"')
    expect(mine).toContain('mode="start"')
    expect(mine).not.toContain('抢夺编队')
    expect(mine).not.toContain('class="pick-list"')
    expect(herb).toContain('<CombatPickSheet')
    expect(herb).toContain('title-text="派去这块地"')
    expect(herb).toContain('confirm-text="除草"')
    expect(herb).toContain('HERB_PVP_COUNTER_RULE')
    expect(herb).toContain('orderHerbPick')
    expect(herb).toContain('herbCounterMark')
    expect(herb).toContain('herbPlotShowsWeakness')
    expect(herb).toContain('herbProbeCells')
    expect(herb).toContain('侦测')
    expect(herb).not.toContain('1格')
    expect(herb).toContain(':recommend-label="markCounter"')
    expect(herb).toContain(':show-runes="false"')
    expect(herb).toContain(':show-assist="false"')
    expect(herb).toContain(':can-pick="canSend"')
    expect(herb).not.toContain('class="pick-list"')
    expect(herb).not.toContain('营地没有满血苦工')
    expect(encounter).not.toContain('orderHerbPick')
    expect(encounter).not.toContain('herbCounterMark')
    expect(mine).not.toContain('orderHerbPick')
    expect(mine).not.toContain('herbCounterMark')
    expect(sheet).toContain("recommend(w) === '克制'")
  })
})
