import { describe, expect, it } from 'vitest'
import encounter from './encounterPanel.vue?raw'
import helpMark from './helpMark.vue?raw'
import sheet from './modeHelpSheet.vue?raw'
import pvp from './pvpPanel.vue?raw'
import station from './stationDetailSheet.vue?raw'
import tech from './techPanel.vue?raw'
import { MODE_HELP, TECH_HELP, modeHelpIdForMainline, modeHelpOf } from './modeHelp'

describe('mode help', () => {
  it('writes the four modes from the current rules', () => {
    for (const help of Object.values(MODE_HELP)) {
      expect(help.rows.map((row) => row.label)).toEqual(['怎么玩', '规则要点', '注意'])
      expect(help.rows.every((row) => row.text.length > 0)).toBe(true)
    }
    const treasure = modeHelpOf('treasure').rows.map((row) => row.text).join('')
    expect(treasure.length).toBeLessThan(220)
    expect(treasure).toContain('10 钻')
    expect(treasure).toContain('行军')
    expect(treasure).not.toContain('出征')
    expect(treasure).toContain('保留战斗中与我方开采')
    expect(treasure).not.toContain('我方开采苦工回休息')
    expect(treasure).toContain('开采不装符文')
    expect(treasure).toContain('抢夺可以装')
    expect(treasure).not.toContain('快照')
    expect(treasure).not.toContain('联机')
    expect(treasure).not.toContain('NPC')
    expect(treasure).not.toContain('假玩家')
    expect(treasure).not.toContain('玩家名')
    expect(treasure).toContain('不能再开')
    expect(treasure).toContain('无人矿')
    expect(treasure).toContain('放弃')
    expect(treasure).toContain('挖出矿石，悬赏可双倍')
    expect(treasure).toContain('一半没有守军')
    expect(treasure).toContain('开采快 1 秒')
    expect(treasure).toContain('战旗栏')
    expect(treasure).toContain('荣誉徽记')
    expect(treasure).not.toContain('三分之一')
    expect(treasure).not.toContain('补采')
    expect(treasure).not.toContain('影矿卫')
    const battle = modeHelpOf('battlefield').rows.map((row) => row.text).join('')
    expect(battle.length).toBeLessThan(180)
    expect(battle).toContain('行军')
    expect(battle).not.toContain('出征')
    expect(battle).toContain('探索')
    expect(battle).toContain('增援')
    expect(battle).toContain('不扣补给')
    expect(battle).toContain('1～3')
    expect(battle).toContain('满血')
    expect(battle).toContain('命中弱点增伤、扣盾')
    expect(battle).toContain('破防硬直')
    expect(battle).toContain('打中未揭示的会揭示')
    const dungeon = modeHelpOf('dungeon').rows.map((row) => row.text).join('')
    expect(dungeon).toContain('两单')
    expect(dungeon).toContain('日切')
    expect(dungeon).toContain('5 人')
    const herb = modeHelpOf('herb').rows.map((row) => row.text).join('')
    expect(herb).toContain('体力 100')
    expect(herb).toContain('花 10')
    expect(herb).toContain('3 分钟回 1')
    expect(herb).toContain('苦工克制这块地的弱点：割草 2 分钟、只扣 7 点体力')
    expect(herb).toContain('不吃弱点')
    expect(herb).toContain('7 或 10')
    expect(herb).toContain('没打死回休息且不扣')
    expect(herb).toContain('对方来撞不改体力')
    expect(herb).not.toContain('体力不退')
    expect(herb).not.toContain('30 分钟回 1')
    expect(herb).not.toContain('除草花 1，')
    const market = modeHelpOf('market').rows.map((row) => row.text).join('')
    expect(market).toContain('当铺')
    expect(market).toContain('限时')
    expect(market).toContain('奖励 ×2')
  })

  it('maps mainline tabs and unknown values onto a help id', () => {
    expect(modeHelpIdForMainline('battlefield')).toBe('battlefield')
    expect(modeHelpIdForMainline('dungeon')).toBe('dungeon')
    expect(modeHelpIdForMainline('market')).toBe('market')
    expect(modeHelpIdForMainline('mine')).toBe('battlefield')
  })

  it('opens the shared sheet from the same question mark', () => {
    expect(sheet).toContain('class="mask"')
    expect(sheet).toContain('<dt>')
    expect(sheet).toContain('关闭')
    expect(sheet).toContain('role="dialog"')
    expect(helpMark).toContain('class="help-mark"')
    expect(helpMark).toContain('border-radius: 50%')
    expect(helpMark).toContain('width: 32px')
    expect(helpMark).toContain('height: 32px')
    expect(helpMark).toContain('aria-label="label"')
    for (const source of [pvp, encounter, tech, station]) {
      expect(source).toContain('<HelpMark')
      expect(source).toContain('<ModeHelpSheet')
      expect(source).toContain('helpOpen')
      expect(source).toContain('page-head')
    }
    expect(pvp).toContain('modeHelpOf(helpId())')
    expect(pvp).toContain("'herb'")
    expect(pvp).toContain("'beast'")
    expect(pvp).toContain("'treasure'")
    expect(encounter).toContain('modeHelpIdForMainline(currentTab.value)')
    expect(encounter).not.toContain('BATTLEFIELD_ACTS.help')
    expect(tech).toContain('TECH_HELP')
    expect(station).toContain('查看${def.label}说明')
    expect(station).not.toContain('class="help-box"')
  })

  it('writes the tech help in three lines from the current rules', () => {
    expect(TECH_HELP.rows).toHaveLength(3)
    expect(TECH_HELP.rows.map((row) => row.label)).toEqual(['灵感', '点亮', '效果'])
    const text = TECH_HELP.rows.map((row) => row.text).join('')
    expect(text).toContain('20')
    expect(text).toContain('酋长每升 1 级再给 1 点')
    expect(text).toContain('不再加')
    expect(text).toContain('同一层都能点')
    expect(text).toContain('开上一层')
    expect(text).toContain('点开节点看效果')
    expect(text).toContain('未解锁')
  })
})
