import { describe, expect, it } from 'vitest'
import panel from './pvpPanel.vue?raw'
import mine from './treasureMinePanel.vue?raw'
import banner from './treasureBannerPanel.vue?raw'
import avatar from './playerAvatar.vue?raw'

describe('pvp treasure tab', () => {
  it('shows 夺宝 and 军械铺 in the PVE-style strip', () => {
    expect(panel).toContain('aria-label="PVP分页"')
    expect(panel).toContain('class="sub"')
    expect(panel).toContain('夺宝')
    expect(panel).toContain('军械铺')
    expect(panel).toContain('战旗')
    expect(panel).toContain('<TreasureMinePanel')
    expect(panel).toContain('<TreasureArmoryPanel')
    expect(panel).toContain('<TreasureBannerPanel')
    expect(panel).toContain("modeHelpOf('banner')")
    expect(mine).toContain('增援 {{ TREASURE_REINFORCE_COST }} 珠宝')
    expect(mine).toContain('补位 {{ TREASURE_FILL_COST }} 珠宝')
    expect(mine).toContain('class="tags"')
    expect(mine).toContain('class="board"')
    expect(mine).toContain('aria-label="宝库"')
    expect(mine).toContain('刷新 {{ TREASURE_REFRESH_SAND_COST }} 砂金')
    expect(mine).toContain('刷新 {{ TREASURE_REFRESH_COST }} 钻')
    expect(mine).toContain("onRefresh('sandGold')")
    expect(mine).toContain("onRefresh('diamonds')")
    expect(mine).toContain('侦察 {{ TREASURE_SCOUT_COST }} 砂金')
    expect(banner).toContain('aria-label="战旗"')
    expect(banner).toContain('已满')
    expect(banner).toContain('is-short')
    expect(banner).toContain('升级 {{ cost() }} 古玉')
    expect(avatar).toContain('frame-copper')
    expect(avatar).toContain('frame-silver')
    expect(avatar).toContain('frame-gold')
    expect(mine).toContain('抢夺 {{ stakeOf(mine) }} 砂金')
    expect(mine).toContain('is-short')
    const tags = mine.slice(mine.indexOf('class="tags"'), mine.indexOf('</span>', mine.indexOf('class="tags"')))
    expect(tags).not.toContain('affix-chip')
    expect(tags).not.toContain('COMBAT_ATTR_LABEL')
    expect(tags).not.toContain('mine.weaknesses')
    expect(mine).toContain('class="weak"')
    expect(mine).toContain('<CombatAttrIcon')
    expect(mine).toContain('mineWeaknessSlots(mine)')
    expect(mine).toContain(':attr="slot"')
    expect(mine).not.toContain('affix-chip')
    expect(mine).toContain('消失倒计时 {{ clock(mine) }}')
    expect(mine).not.toContain('剩余 {{ clock(mine) }}')
  })
})
