import { describe, expect, it } from 'vitest'
import { createSave, normalizeDiamonds } from './createSave'
import { spawnWorker } from './recruit'
import { PLAYABLE_STATION_IDS, START_DIAMONDS, START_GOLD, START_TECH_POINTS, STATION_IDS, WORKER_QUALITY_REV } from './tables'

describe('createSave diamonds', () => {
  it('starts diamonds at 0 as a premium-token placeholder', () => {
    const save = createSave()
    expect(save.diamonds).toBe(START_DIAMONDS)
    expect(save.diamonds).toBe(0)
    expect(save.gold).toBe(START_GOLD)
  })

  it('normalizes missing or dirty diamonds back to 0', () => {
    expect(normalizeDiamonds(undefined)).toBe(0)
    expect(normalizeDiamonds(null)).toBe(0)
    expect(normalizeDiamonds(-3)).toBe(0)
    expect(normalizeDiamonds(Number.NaN)).toBe(0)
    expect(normalizeDiamonds(4.8)).toBe(4)
  })
})

describe('createSave six stations', () => {
  it('opens with the six stations and empty dual slots', () => {
    const save = createSave()
    expect(STATION_IDS).toEqual(['mining', 'forging', 'hunting', 'cooking', 'herbalism', 'alchemy'])
    expect(Object.keys(save.stations)).toEqual(STATION_IDS)
    expect(PLAYABLE_STATION_IDS).toContain('hunting')
    expect(PLAYABLE_STATION_IDS).toContain('herbalism')
    expect((save.stations as Record<string, unknown>).woodcutting).toBeUndefined()
    expect((save.stations as Record<string, unknown>).fishing).toBeUndefined()
    expect(save.potionSlots).toEqual([null, null, null, null])
    expect(save.stations.mining.miningNode?.nodeHp).toBe(20)
    expect(save.stations.mining.miningNode?.recoverAt).toBeNull()
    expect(save.rngState).not.toBe(0)
    expect(save.rngState).not.toBe(1)
    expect(save.forgedTools).toEqual([])
    expect(save.stations.forging.selectedToolType).toBe('pick')
    expect(save.stations.forging.selectedForgeToolId).toBeNull()
    expect(save.stations.forging.selectedCategory).toBe('default')
    expect(save.stations.forging.unlockedCategories).toEqual(['default'])
    expect(save.stations.hunting.selectedCategory).toBe('copper')
    expect(save.stations.cooking.selectedCategory).toBe('copper')
    expect(save.stations.cooking.unlockedCategories).toEqual(['copper', 'iron'])
    const worker = spawnWorker(save)
    expect(worker.foodSlot).toBeNull()
    expect(worker.fatigueDebt).toBe(0)
    expect(save.potionSlots).toEqual([null, null, null, null])
    expect(save.potionBuffs.stimUntil).toBeNull()
    expect(save.potionBuffs.focusConsumed).toEqual([])
    expect(save.stations.mining.fatigueCombo).toEqual({ streak: 0, key: null, frustration: 0, fog: 0 })
    expect(save.stations.mining.selectedToolId).toBeNull()
    expect(save.stations.forging.selectedToolId).toBeNull()
    expect(worker.qualityTier).toBe(1)
    expect(worker.level).toBe(1)
    expect(worker.xp).toBe(0)
    expect(save.workerQualityRev).toBe(WORKER_QUALITY_REV)
    expect(save.knightLevel).toBe(1)
    expect(save.techPoints).toBe(START_TECH_POINTS)
    expect(save.techPoints).toBe(20)
    expect(save.unlockedTechIds).toEqual([])
    expect(save.techLevels).toEqual({})
    expect(save.encounters).toHaveLength(2)
    expect(save.encounters.every((enc) => enc.kind === 'enemy')).toBe(true)
    expect(save.marketEncounters).toHaveLength(1)
    expect(save.marketEncounters[0].kind).toBe('pawn')
    if (save.marketEncounters[0].kind === 'pawn') {
      expect(save.marketEncounters[0].pawnWants).toEqual({ ore: 2 })
    }
    expect(save.mainChapter).toBe(1)
    expect(save.mainLootClaims).toBe(0)
    expect(save.guideQuestStep).toBe(1)
    expect(save.guideQuestRev).toBe(2)
    expect(save.guideQuestPotionUsed).toBe(false)
    expect(save.starterCopperPawnDone).toBe(false)
    expect(save.stations.herbalism.stationLevel).toBe(1)
  })
})
